name: 'text-summarizer-api'

services:

  web:
    build:
      context: ./project
      dockerfile: docker/dev.Dockerfile
    container_name: dev-api
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project/app:/opt/project/app
      - ./project/tests:/opt/project/tests
      - ./project/pyproject.toml:/opt/project/pyproject.toml
      - ./project/migrations:/opt/project/migrations
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DOCS_URL=/docs
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev       
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test  
      - REDIS_ENDPOINT=web-redis:6379
      - REDIS_PASSWORD=redis
    depends_on:
      - web-db
      - web-redis

  web-db:
    build:
      context: ./project
      dockerfile: docker/db.Dockerfile
    container_name: db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web-redis:
    image: redis:bookworm # This should match the debian version used in dev.Dockerfile and db.Dockerfile 
    container_name: redis
    expose:
      - 6379 # Expose redis port for internal docker network communication between services
    command: ["redis-server", "--requirepass", "redis"]
